# Pre-commit hooks for brutus
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']  # Warn if files > 1MB
      - id: check-merge-conflict
      - id: check-toml
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        args: ['--line-length=88']

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length', '88']

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ['--max-line-length=88', '--max-complexity=15', '--extend-ignore=E203,W503,C901,E501']
        # E203: whitespace before ':' (conflicts with black)
        # W503: line break before binary operator (conflicts with black)
        # C901: complexity checks disabled for scientific algorithms
        # E501: line length disabled (LaTeX equations, URLs in docstrings)
        exclude: ^(tests/|run_coverage\.py)
        # Tests and coverage scripts have relaxed linting rules
